# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  contrast-oss-scan:
    name: Run Contrast OSS Scan
    runs-on: ubuntu-latest
    env:
      CONTRAST_ORGANIZATION_ID: 05f247b3-a388-4928-90f6-15a0dd2d997f
      CONTRAST_API_URL: https://apptwo.contrastsecurity.com
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        
      - name: Contrast Security SCA
        # You may pin to the exact commit or the version.
        # uses: Contrast-Security-OSS/contrast-sca-action@0a234a04ffdff74336bb242f1898820c87de90e2
        uses: Contrast-Security-OSS/contrast-sca-action@v1
        with:
          # An agent API key provided by Contrast (required).
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          # User authorization credentials provided by Contrast (required).
          authHeader: ${{ secrets.CONTRAST_USER_AUTH_HEADER }}
          # The ID of your organization in Contrast (required).
          orgId: $CONTRAST_ORGANIZATION_ID
          # Specify the directory in which to search for project configuration files (required).
          filePath: .
          # The name of the host. Includes the protocol section of the URL (https://). Defaults to https://ce.contrastsecurity.com. (optional)
          apiUrl: $CONTRAST_API_URL
          # Allows user to report libraries with vulnerabilities above a chosen severity level. Values for level are high, medium or low. (Note: Use this input in combination with the fail input, otherwise the action will exit)
          #severity: # optional
          # When set to true, fails the action if CVEs have been detected that match at least the severity option specified.
          fail: false# optional
          # When set to true, excludes developer dependencies from the results.
          #ignoreDev: # optional
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O webgoat.jar https://github.com/WebGoat/WebGoat/releases/download/v8.2.2/webgoat-server-8.2.2.jar
          
      - name: Contrast Scan Analyze
        # You may pin to the exact commit or the version.
        # uses: Contrast-Security-OSS/contrastscan-action@ede6d65addebe0898291fbe640850556d914be18
        uses: Contrast-Security-OSS/contrastscan-action@v2.0.3
        with:
          # An agent API key provided by Contrast (required).
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          # User authorization credentials provided by Contrast (required).
          authHeader: ${{ secrets.CONTRAST_USER_AUTH_HEADER }}
          # The ID of your organization in Contrast (required).
          orgId: $CONTRAST_ORGANIZATION_ID
          # The name of the host. Includes the protocol section of the URL (https://). Defaults to https://ce.contrastsecurity.com. (optional)
          #apiUrl: $CONTRAST_API_URL
          apiUrl: https://apptwo.contrastsecurity.com
          # The Artifact to Scan on the Contrast Platform.
          artifact: webgoat.jar
          # The name of the project you want to scan in Contrast.
          projectName: fromGithub # optional
          # The ID of your project in Contrast.
          #projectId: # optional
          # The language of your project.
          #language: # optional
          # Set a specific time span (in seconds) before the function times out. The default timeout is 5 minutes if timeout is not set.
          #timeout: # optional, default is 300
          # Allows user to report vulnerabilities above a chosen severity level. Values for level are high, medium or low. (Note: Use this input in combination with the fail input, otherwise the action will exit)
          #severity: # optional
          # When set to true, fails the action if CVEs have been detected that match at least the severity option specified.
          fail: false # optional
          
        
